### ISSUE TITLE
Autosave / Quickly save from the pd system menu

### ISSUE THREAD

**Issue by psychicteeth** [orllewin/modular_play_public#44]
With many crashes and bugs happening, it would be useful to have a versioned autosave (this would also be helpful for bug repro), or to be able to quickly save a new version of a piece, as navigating to the file menu frequently can take some time. Would it be possible to add an auto save that records the last 10 or so modifications to a piece, and/or be able to save a new version of a piece quickly from the playdate system menu?

**Comment by orllewin** [comment]
Problem is saving is quite intensive, so a periodic autosave would result in frame drops (Playdate is single threaded). Better to keep fixing the bugs - next release has a lot of fixes in, particularly bad state problems that happen when deleting modules. A save option in the main menu would be good though, I'll add that.
