### ISSUE TITLE
Crash turning an Output Single module volume up past 100

### ISSUE THREAD

**Issue by psychicteeth** [orllewin/modular_play_public#46]
It's one louder!

Place an Output Single module (may work with other output modules? not tested)
Connect any input to the output module to enable the volume controls
Use the menu to set the volume to 100
Use the menu to raise the volume with Volume Up
Observe crash.

**Comment by orllewin** [comment]
Good catch:

```
Modules/Mixers/Mixer1/mix1_mod.lua:185: method 'volumeUp' is not callable (a nil value)
stack traceback:
	Modules/Mixers/Mixer1/mix1_mod.lua:185: in upvalue 'onAction'
	Modules/module_menu.lua:60: in field 'onSelect'
	CoracleViews/text_list.lua:169: in method 'tapA'
	Modules/module_menu.lua:73: in function <Modules/module_menu.lua:72>
```

That module shouldn't have the menu options, must have been copy/paste

Fixed in 0.0.14-Alpha (coming soon)
